### DISCUSSION TITLE
Discrepancy in logs w.r.t learning rate

### DISCUSSION THREAD

**Discussion by rezafuru** [yoshitomo-matsubara/torchdistill#242] [Q&A] [answered]
Hi,

I've been running some experiments and noticed that the logs give me a different learning rate then what I specified in the config. For example:
```
    optimizer:
      type: 'Adam'
      params:
        lr: 0.001
    scheduler:
      type: 'MultiStepLR'
      params:
        milestones: [6, 9]
        gamma: 0.1
```

Yields `2022/08/20 14:11:44	INFO	torchdistill.misc.log	Epoch: [2]  [100/782]  eta: 0:01:08  lr: 1e-05` in the logs. Stepping through the debugger, it does seem like the optimizer was correctly initiallized. However, the training box seems to store a different lr in its param groups, which is what is logged in the end (`metric_logger.update(loss=loss.item(), lr=training_box.optimizer.param_groups[0]['lr'])`)

Does anyone know whether I'm misunderstanding the configuration, or is this a potential bug? Note, regardless of what I set the lr in the config, the logger keeps outputting `lr: 1e-05`
