### DISCUSSION TITLE
Scheduler

### DISCUSSION THREAD

**Discussion by Adesh696** [yoshitomo-matsubara/torchdistill#362] [Q&A] [answered]
How can I use a different scheduler like ReduceLROnPlateau?

**Comment by yoshitomo-matsubara** [comment]
Hi @Adesh696 ,

For torchdistill <= 0.33, you can use built-in PyTorch schedulers simply by specifying the class name and kwargs like this

e.g, [MultiStepLR](https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.MultiStepLR.html) for [final training densenet_bc_k12](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/legacy/sample/cifar10/ce/densenet_bc_k12_depth100-final_run.yaml#LL81C1-L85C17)

```yaml
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [150, 225]
      gamma: 0.1
``` 

If you want to use [ReduceLROnPlateau](https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.ReduceLROnPlateau.html#torch.optim.lr_scheduler.ReduceLROnPlateau), then you will need to replace the scheduler entry with
```yaml
  scheduler:
    type: 'ReduceLROnPlateau'
    params:
      mode: 'min'
      factor: 0.1
      # ... other kwargs for instantiating ReduceLROnPlateau (except optimizer) e.g., threshold, threshold_mode, cooldown, min_lr, eps, verbose, if necessary

```
