### DISCUSSION TITLE
Distilling VIT-L from VIT-G on imagenet

### DISCUSSION THREAD

**Discussion by nighting0le01** [yoshitomo-matsubara/torchdistill#374] [Q&A] [answered]
Hi, How can modify the config files to Distill from a ViT-g model pretrained on Imagenet21k& finetuned on Imagenet 1k to a VIT-L model. 
What All do I need to modify
both checkpoints are avaialble here https://github.com/huggingface/pytorch-image-models

**Comment by yoshitomo-matsubara** [comment, marked as answer]
Hi @arpitsahni04 

Do you just want to change models in some ImageNet configs?
If so, with the current PyPI package (torchdistill==0.3.3), your model entry in a yaml config will look like this as shown in [README.md](https://github.com/yoshitomo-matsubara/torchdistill#pytorch-hub)

```
models:
  teacher_model:
    name: 'vit_giant_patch14_224'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      pretrained: True
      other kwargs here if necessary ...
  student_model:
    name: 'vit_large_patch14_clip_224'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      pretrained: False
      other kwargs here if necessary ...
```

For the teacher and student names, I referred to https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/vision_transformer.py

Note that if you'll need to tune hyperparameters if you reuse existing yaml config files under `sample/` like [this](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/legacy/sample/ilsvrc2012/single_stage/kd/resnet18_from_resnet152.yaml)

**Reply by nighting0le01** [reply]
Hi @yoshitomo-matsubara yes I want to run experiments on ImageNet 1k with vit-g and vit-L: 


the sample file you referenced in your post doesn't have repo_or_dir key. also do i need to edit the config and give it to this:[image_classification.py](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/examples/legacy/image_classification.py)


```
models:
  teacher_model:
    name: &teacher_model_name 'resnet152'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'resnet18'
    params:
      num_classes: 1000
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/single_stage/kd/', *student_experiment, '.pt']
```
2.  how do I just evalute a distilled model on imagenet validation set.

**Reply by nighting0le01** [reply]
Also @yoshitomo-matsubara 
where can i get the right hyperparameters to compare 
google/vit-large-patch16-224
finetuned via distillation on imagenet 1k with google/vit-large-patch16-224-in21k

**Reply by yoshitomo-matsubara** [reply]
Hi @arpitsahni04 
1. You replace whole `models` entry with one I provied above, and you give the yaml config to image_classification.py with `--config` 
2. If you want to skip training, add `-test_only` and `-student_only` 
3. Check `timm` documentation and its original papers for hyperparameters they used. I've never used these specific models

**Reply by nighting0le01** [reply]
Thanks @yoshitomo-matsubara  alot what are other kwargs? can you share the entire template for it so i can go through it and give the right parameters?
```

models:
  teacher_model:
    name: 'vit_giant_patch14_224'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      pretrained: True
      other kwargs here if necessary ...
  student_model:
    name: 'vit_large_patch14_clip_224'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      pretrained: False
      other kwargs here if necessary ...
```

Also how do i use models from hugging face hub: example https://huggingface.co/google/vit-large-patch16-224-in21k or https://huggingface.co/google/vit-large-patch16-224 what repo_or_dir and name do i need
