### DISCUSSION TITLE
Multi-GPU training on same machine is getting stuck

### DISCUSSION THREAD

**Discussion by nighting0le01** [yoshitomo-matsubara/torchdistill#378] [Q&A] [answered]
![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/82f153ad-f633-4dcb-8beb-07fe453c8595)
![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/d01d7df4-7d9e-4f53-8f2c-3fa16e4c9eb2)
![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/79facad0-e040-47b7-8acc-cd49a1d97141)
I'm trying to train on gpu 3,4 on a machine with 8 gpu

**Comment by yoshitomo-matsubara** [comment]
It seems you're using your own scripts (`distillation_expts_image_class.py`). I cannot help you without knowing what changes you made in the script and exact yaml configs. Please share them here as files, not screenshots. 

Please do not use screenshots to show the logs or files, but use texts for better search experience to help others find this discussion when they face similar issues.

Also, please complete other discussions you opened at first and do not leave them unattended. Respect my time for OSS as well.

**Reply by nighting0le01** [reply]
Hi @yoshitomo-matsubara  i apologize for starting this discussion without closing the previous one but I can't get to it before I complete this. please help me solve this issue
yaml:
```
datasets:
  ilsvrc2012:
    name: &dataset_name 'image_net'
    type: 'ImageFolder'
    root: &root_dir !join ['/home/asahni795/data/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        params:
          root: !join [*root_dir, '/train']
          transform_params:
            - type: 'Resize'
              params:
                size: 248
                #interpolation: 'InterpolationMode.BICUBIC'
            - type: 'CenterCrop'
              params:
                size: [224, 224]
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [0.4815, 0.4578, 0.4082]
                std: [0.2686, 0.2613, 0.2758]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: 224
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'eva_giant_patch14_224'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt:

  student_model:
    name: &student_model_name 'vit_large_patch16_224_in21k'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: 

train:
  log_freq: 100
  num_epochs: 20
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 64
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 32
    num_workers: 8
  teacher:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: False
  student:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    type: 'AdamW'
    params:
      lr: 0.001
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [5, 15]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'KDLoss'
        params:
          temperature: 1.0
          alpha: 0.5
          reduction: 'batchmean'
      factor: 1.0
    sub_terms:

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 128
    num_workers: 8
```




image_classification.py
```
import argparse
import datetime
import os
import time

import torch
from torch import distributed as dist
from torch.backends import cudnn
from torch.nn import DataParallel
from torch.nn.parallel import DistributedDataParallel

from torchdistill.common import file_util, yaml_util, module_util
from torchdistill.common.constant import def_logger
from torchdistill.common.main_util import is_main_process, init_distributed_mode, load_ckpt, save_ckpt, set_seed
from torchdistill.core.distillation import get_distillation_box
from torchdistill.core.training import get_training_box
from torchdistill.datasets import util
from torchdistill.eval.classification import compute_accuracy
from torchdistill.misc.log import setup_log_file, SmoothedValue, MetricLogger
from torchdistill.models.official import get_image_classification_model
from torchdistill.models.registry import get_model

logger = def_logger.getChild(__name__)


def get_argparser():
    parser = argparse.ArgumentParser(description='Knowledge distillation for image classification models')
    parser.add_argument('--config', required=True, help='yaml file path')
    parser.add_argument('--device', default='cuda', help='device')
    parser.add_argument('--log', help='log file path')
    parser.add_argument('--start_epoch', default=0, type=int, metavar='N', help='start epoch')
    parser.add_argument('--seed', type=int, help='seed in random number generator')
    parser.add_argument('-test_only', action='store_true', help='only test the models')
    parser.add_argument('-student_only', action='store_true', help='test the student model only')
    parser.add_argument('-log_config', action='store_true', help='log config')
    # distributed training parameters
    parser.add_argument('--world_size', default=1, type=int, help='number of distributed processes')
    parser.add_argument('--dist_url', default='env://', help='url used to set up distributed training')
    parser.add_argument('-adjust_lr', action='store_true',
                        help='multiply learning rate by number of distributed processes (world_size)')
    parser.add_argument('--save_dir',type =str,default="/home/asahni795/workspace/distllation/model_checkpoints" )
    # log_folder = f"../log_folder/{parser.config[models][student_model][name]}_log.txt"
    parser.set_defaults(test_only=False, student_only=False, log="../log_folder/log_eva_distilled_vit_l_8_workers.txt")
    return parser


def load_model(model_config, device, distributed):
    model = get_image_classification_model(model_config, distributed)
    if model is None:
        repo_or_dir = model_config.get('repo_or_dir', None)
        print(model_config.keys())
        model = get_model(model_config['name'], repo_or_dir, **model_config['params'])

    ckpt_file_path = model_config['ckpt']
    load_ckpt(ckpt_file_path, model=model, strict=True)
    return model.to(device)


def train_one_epoch(training_box, device, epoch, log_freq):
    metric_logger = MetricLogger(delimiter='  ')
    metric_logger.add_meter('lr', SmoothedValue(window_size=1, fmt='{value}'))
    metric_logger.add_meter('img/s', SmoothedValue(window_size=10, fmt='{value}'))
    header = 'Epoch: [{}]'.format(epoch)
    for sample_batch, targets, supp_dict in \
            metric_logger.log_every(training_box.train_data_loader, log_freq, header):
        start_time = time.time()
        sample_batch, targets = sample_batch.to(device), targets.to(device)
        loss = training_box(sample_batch, targets, supp_dict)
        training_box.update_params(loss)
        batch_size = sample_batch.shape[0]
        metric_logger.update(loss=loss.item(), lr=training_box.optimizer.param_groups[0]['lr'])
        metric_logger.meters['img/s'].update(batch_size / (time.time() - start_time))
        if (torch.isnan(loss) or torch.isinf(loss)) and is_main_process():
            raise ValueError('The training loop was broken due to loss = {}'.format(loss))


@torch.inference_mode()
def evaluate(model, data_loader, device, device_ids, distributed, log_freq=1000, title=None, header='Test:'):
    model.to(device)
    if distributed:
        model = DistributedDataParallel(model, device_ids=device_ids)
    elif device.type.startswith('cuda'):
        model = DataParallel(model, device_ids=device_ids)

    if title is not None:
        logger.info(title)

    model.eval()
    metric_logger = MetricLogger(delimiter='  ')
    for image, target in metric_logger.log_every(data_loader, log_freq, header):
        image = image.to(device, non_blocking=True)
        target = target.to(device, non_blocking=True)
        output = model(image)
        acc1, acc5 = compute_accuracy(output, target, topk=(1, 5))
        # FIXME need to take into account that the datasets
        # could have been padded in distributed setup
        batch_size = image.shape[0]
        metric_logger.meters['acc1'].update(acc1.item(), n=batch_size)
        metric_logger.meters['acc5'].update(acc5.item(), n=batch_size)

    # gather the stats from all processes
    metric_logger.synchronize_between_processes()
    top1_accuracy = metric_logger.acc1.global_avg
    top5_accuracy = metric_logger.acc5.global_avg
    logger.info(' * Acc@1 {:.4f}\tAcc@5 {:.4f}\n'.format(top1_accuracy, top5_accuracy))
    return metric_logger.acc1.global_avg


def train(teacher_model, student_model, dataset_dict, ckpt_file_path, device, device_ids, distributed, config, args):
    logger.info('Start training')
    train_config = config['train']
    lr_factor = args.world_size if distributed and args.adjust_lr else 1
    training_box = get_training_box(student_model, dataset_dict, train_config,
                                    device, device_ids, distributed, lr_factor) if teacher_model is None \
        else get_distillation_box(teacher_model, student_model, dataset_dict, train_config,
                                  device, device_ids, distributed, lr_factor)
    best_val_top1_accuracy = 0.0
    optimizer, lr_scheduler = training_box.optimizer, training_box.lr_scheduler
    if file_util.check_if_exists(ckpt_file_path):
        best_val_top1_accuracy, _, _ = load_ckpt(ckpt_file_path, optimizer=optimizer, lr_scheduler=lr_scheduler)

    log_freq = train_config['log_freq']
    student_model_without_ddp = student_model.module if module_util.check_if_wrapped(student_model) else student_model
    start_time = time.time()
    for epoch in range(args.start_epoch, training_box.num_epochs):
        training_box.pre_process(epoch=epoch)
        train_one_epoch(training_box, device, epoch, log_freq)
        val_top1_accuracy = evaluate(student_model, training_box.val_data_loader, device, device_ids, distributed,
                                     log_freq=log_freq, header='Validation:')
        if val_top1_accuracy > best_val_top1_accuracy and is_main_process():
            logger.info('Best top-1 accuracy: {:.4f} -> {:.4f}'.format(best_val_top1_accuracy, val_top1_accuracy))
            logger.info('Updating ckpt at {}'.format(ckpt_file_path))
            best_val_top1_accuracy = val_top1_accuracy
            save_ckpt(student_model_without_ddp, optimizer, lr_scheduler,
                      best_val_top1_accuracy, config, args, ckpt_file_path)
        training_box.post_process()

    if distributed:
        dist.barrier()

    total_time = time.time() - start_time
    total_time_str = str(datetime.timedelta(seconds=int(total_time)))
    logger.info('Training time {}'.format(total_time_str))
    training_box.clean_modules()


def main(args):
    log_file_path = args.log
    if is_main_process() and log_file_path is not None:
        setup_log_file(os.path.expanduser(log_file_path))

    distributed, device_ids = init_distributed_mode(args.world_size, args.dist_url)
    logger.info(args)
    cudnn.benchmark = True
    set_seed(args.seed)
    config = yaml_util.load_yaml_file(os.path.expanduser(args.config))
    device = torch.device(args.device)
    dataset_dict = util.get_all_datasets(config['datasets'])
    models_config = config['models']
    teacher_model_config = models_config.get('teacher_model', None)
    teacher_model =\
        load_model(teacher_model_config, device, distributed) if teacher_model_config is not None else None
    student_model_config =\
        models_config['student_model'] if 'student_model' in models_config else models_config['model']
    ckpt_file_path = student_model_config['ckpt']
    student_model = load_model(student_model_config, device, distributed)
    if args.log_config:
        logger.info(config)

    if not args.test_only:
        train(teacher_model, student_model, dataset_dict, ckpt_file_path, device, device_ids, distributed, config, args)
        student_model_without_ddp =\
            student_model.module if module_util.check_if_wrapped(student_model) else student_model
        load_ckpt(student_model_config['ckpt'], model=student_model_without_ddp, strict=True)

    test_config = config['test']
    test_data_loader_config = test_config['test_data_loader']
    test_data_loader = util.build_data_loader(dataset_dict[test_data_loader_config['dataset_id']],
                                              test_data_loader_config, distributed)
    log_freq = test_config.get('log_freq', 1000)
    if not args.student_only and teacher_model is not None:
        evaluate(teacher_model, test_data_loader, device, device_ids, distributed, log_freq=log_freq,
                 title='[Teacher: {}]'.format(teacher_model_config['name']))
    evaluate(student_model, test_data_loader, device, device_ids, distributed, log_freq=log_freq,
             title='[Student: {}]'.format(student_model_config['name']))


if __name__ == '__main__':
    argparser = get_argparser()
    main(argparser.parse_args())
```


Error--
```
torchrun --nproc_per_node=2 image_classification.py --world_size 2 --config vitg-vitL.yaml 
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/asahni795/.conda/envs/env_2/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/asahni795/.conda/envs/env_2/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")
/home/asahni795/.conda/envs/env_2/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/asahni795/.conda/envs/env_2/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")
2023/07/25 13:33:12     INFO    torchdistill.common.main_util   | distributed init (rank 1): env://
2023/07/25 13:33:12     INFO    torch.distributed.distributed_c10d      Added key: store_based_barrier_key:1 to store for rank: 1
2023/07/25 13:33:12     INFO    torchdistill.common.main_util   | distributed init (rank 0): env://
2023/07/25 13:33:12     INFO    torch.distributed.distributed_c10d      Added key: store_based_barrier_key:1 to store for rank: 0
2023/07/25 13:33:12     INFO    torch.distributed.distributed_c10d      Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2023/07/25 13:33:12     INFO    torch.distributed.distributed_c10d      Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
```


Also even for Single GPU Run on A100 GPU . the img/s seems too low for the same config . what can be the issue? how can i increase it? I saw in you configs it was upto 500 img/s on imagenet 1k

**Reply by yoshitomo-matsubara** [reply]
At first glance, there seems to be no changes made in `image_classification.py`. If you made changes in the script, explain the changes.

If not, I suggest you use `CUDA_DEVICE_IDS=0,1 python3 -m torch.distributed.launch --nproc_per_node=2 --use_env` instead of `torchrun --nproc_per_node=2 ` because you are supposed to use a little bit old torch for torchdistill v0.3.3 and did not even reach `logger.info(args)`, and the issue may be from distributed training mode

**Reply by nighting0le01** [reply]
Hi I used the command you suggested but 
```
 CUDA_DEVICE_IDS=0,1 python3 -m torch.distributed.launch --nproc_per_node=2 --use_env distillation_expts_image_class.py --world_size 2 --config vitg-vitL.yaml
/home/asahni795/.conda/envs/tf/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2023/07/25 15:49:34     INFO    torchdistill.common.main_util   | distributed init (rank 0): env://
2023/07/25 15:49:34     INFO    torch.distributed.distributed_c10d      Added key: store_based_barrier_key:1 to store for rank: 0
2023/07/25 15:49:34     INFO    torchdistill.common.main_util   | distributed init (rank 1): env://
2023/07/25 15:49:34     INFO    torch.distributed.distributed_c10d      Added key: store_based_barrier_key:1 to store for rank: 1
2023/07/25 15:49:34     INFO    torch.distributed.distributed_c10d      Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2023/07/25 15:49:34     INFO    torch.distributed.distributed_c10d      Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
```
can you share some conda yml env file for the enviornment you want me try with?

**Reply by yoshitomo-matsubara** [reply]
I have no conda yaml env file for such purposes.

1. Have you ever successfully completed model training in PyTorch's distributed training mode on the same machine?
2. Did you confirm that the GPUs are not used by any other processes?
3. If yes for 2, I'd suggest you run PyTorch's sample script in distributed training model with some random large models  and compare the behavior https://github.com/pytorch/vision/blob/main/references/classification/train.py

**Reply by nighting0le01** [reply]
1. yes distributed model training has been completed on this machine example yolo v8 from ultralytics
2. yes i'm these 2 gpu from inside a docker container on the machine
Can you provide suggested torch and cuda version? I think that might be an issue. also do i need to set any additional env variables in the image_classification.py file?
3. Also how much img/s can we expect from imagenet on A100 . using more than 8 worker detoriates img/s

**Reply by yoshitomo-matsubara** [reply]
I've never used docker for torchdistill. There should be no additional env variables, and I do not have good estimate for img/s for A100.

You still don't answer my 2nd question. Did you confirm that no other processes used the two GPUs when you ran the script?
For v0.3.3, I used to use CUDA 10.2 if I remember correctly.

Again, I suggest you run PyTorch's sample script in distributed training model with some random large models and compare the behavior https://github.com/pytorch/vision/blob/main/references/classification/train.py to make sure that it is not a torchdistill-specific issue.

**Reply by nighting0le01** [reply]
yes I did confirm that both GPU were idle. when I used 
```
python -m torch.distributed.launch --nproc_per_node=1 --use_env distillation_expts_image_class.py --world_size 1 --config  vitg-vitL.yaml  
```
training did start but not when world size is more than 1 or nproc_per_node is more than 1

```
(tf) asahni795@464b02714931:~/workspace/distllation/code_folder$ python -m torch.distributed.launch --nproc_per_node=2 --use_env distillation_expts_image_class.py --world_s
ize 2 --config  vitg-vitL.yaml 
/home/asahni795/.conda/envs/tf/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2023/07/25 19:20:00     INFO    torchdistill.common.main_util   | distributed init (rank 1): env://
2023/07/25 19:20:00     INFO    torch.distributed.distributed_c10d      Added key: store_based_barrier_key:1 to store for rank: 1
2023/07/25 19:20:00     INFO    torchdistill.common.main_util   | distributed init (rank 0): env://
2023/07/25 19:20:00     INFO    torch.distributed.distributed_c10d      Added key: store_based_barrier_key:1 to store for rank: 0
2023/07/25 19:20:00     INFO    torch.distributed.distributed_c10d      Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
2023/07/25 19:20:00     INFO    torch.distributed.distributed_c10d      Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
```
gets stuck here all the time.

**Reply by yoshitomo-matsubara** [reply]
Try this at first
> Again, I suggest you run PyTorch's sample script in distributed training model with some random large models and compare the behavior https://github.com/pytorch/vision/blob/main/references/classification/train.py to make sure that it is not a torchdistill-specific issue.

**Reply by nighting0le01** [reply]
I tried with this script also, only single nproc seems to be working. Do i need to define any additional enviornment variables like RANK or LocaL HOST

![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/fe11aa41-c82f-474f-a8dd-987321646887)

also can we enable --amp in torchdistill. the img/s on imagenet is also pretty good on the original script: https://github.com/pytorch/vision/blob/main/references/classification/train.py
what can i do differently to get img/s higher (I'm getting like 12 img/s :( )and multi gpu run working 

![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/2e4e92b7-3cf1-4fb2-a36d-162e272a36ac)
please help

**Reply by yoshitomo-matsubara** [reply, marked as answer]
Based on your results with train.py in torchvision, I think the problem is caused by your (docker) environment, and I do not have the right answer for this.

torchdistill no longer supports amp because it supports Hugging Face accelerate instead. See https://github.com/yoshitomo-matsubara/torchdistill/discussions/247

**Reply by nighting0le01** [reply]
Hey @yoshitomo-matsubara  this is what I found to be the reason:https://github.com/Lightning-AI/lightning/discussions/11865#discussioncomment-4759428 is that the case for torchdistill imagenet.

Also do I need to define Local Host or master addr env variables??

**Reply by yoshitomo-matsubara** [reply]
I don't think it is the case because `distributed, device_ids = init_distributed_mode(args.world_size, args.dist_url)` where I assume you got stuck has nothing to do with the dataset process, AND  `ImageFolder` class does not pre-load the images, but loads sample images at every `__getitem__` call. 

**And again, your results with train.py in torchvision suggests it's not caused by torchdistill. If you find a solution that works for `train.py` in torchvision, I think it would work for torchdistill as well.** Since it seems like a docker-specific problem, I don't have the right answer as said above.

**Reply by nighting0le01** [reply]
Thanks @yoshitomo-matsubara 
I see your point thanks alot but can you please clarify if i need to explicity specify:
```
os.environ['MASTER_ADDR'] = "localhost"
os.environ["MASTER_PORT"] = "12355"
```

**Reply by yoshitomo-matsubara** [reply]
As repeatedly said, I do not have the right answer as I've never faced situations that require us to explicitly specify the env variables for DDP. It may work or may not work.

**Reply by nighting0le01** [reply]
> As repeatedly said, I do not have the right answer as I've never faced situations that require us to explicitly specify the env variables for DDP. It may work or may not work. 

Ok thanks @yoshitomo-matsubara  but can you suggest why the img/s is low in torchdistill as compared to torchvision train.py on the same machine and dataset and same model also. How can I improve img/s

**Reply by yoshitomo-matsubara** [reply]
Numbers I usually see are 400-500 img/s, and I've never seen such low latency like 12 img/s. Since your (docker) environment is somewhat unique, I don't think I can help you find answers for the mysteries. I'd use conda or pipenv instead of docker and compare the behavior.

**Reply by nighting0le01** [reply]
-- I tried running outside the container also, same results torchvision works on single gpu with high img/s , torchdistill is slow at around 15-16 img/s . both don't work in multi gpu setting and get stuck like this :
![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/35a62178-b440-4b66-8fd3-10215d47e9dc)


 torchvision does work well on single gpu inside & outside the same docker enviornment. its only torchdistill runs that seem slower.  can it be due to the config file:
```
datasets:
  ilsvrc2012:
    name: &dataset_name 'image_net'
    type: 'ImageFolder'
    root: &root_dir !join ['/home/asahni795/data/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        params:
          root: !join [*root_dir, '/train']
          transform_params:
            - type: 'Resize'
              params:
                size: 248
            - type: 'CenterCrop'
              params:
                size: [224, 224]
            # - type: 'RandomHorizontalFlip'
            #   params:
            #     p: 0.5
            - &totensor
              type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [0.4815, 0.4578, 0.4082]
                std: [0.2686, 0.2613, 0.2758]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: 224
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'eva_giant_patch14_224'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt:

  student_model:
    name: &student_model_name 'vit_large_patch16_224_in21k'
    repo_or_dir: 'huggingface/pytorch-image-models'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: 

train:
  log_freq: 10
  num_epochs: 20
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 84
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 32
    num_workers: 8
  teacher:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: False
  student:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    type: 'SGD'
    params:
      lr: 0.001
      momentum: 0.9
      weight_decay: 0.0005

  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [1, 2]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'KDLoss'
        params:
          temperature: 1.0
          alpha: 0.5
          reduction: 'batchmean'
      factor: 1.0
    sub_terms:

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 128
    num_workers: 8
```

or env
```

```
