### ISSUE TITLE
How to use different methods for a single task?

### ISSUE THREAD

**Issue by AndyFrancesco29** [yoshitomo-matsubara/torchdistill#132]
Hi,
As mentioned, torchdistill offers various KD methods. So is it possible to assign different KD methods like fitnet or contrastive learning method for a specific task like image classification? Thank you.

**Comment by yoshitomo-matsubara** [comment]
Hi @AndyFrancesco29 ,

Definitely, you can use different KD methods for a specific task since the methods in torchdistill are implemented in a model-agnostic way.
Do you have any specific configuration in your mind?  (e.g., a set of models, method, task, etc that you're interested in)
If so, I can give you a more concrete advice.

**Comment by AndyFrancesco29** [comment]
Hi @yoshitomo-matsubara ,
Thanks for your reply. I mean for example in RepDistiller repo, it has an input parameter "--distill" to indicate which method to use, like Fitnet or vanilla KD. Is that an option in config file? Thank you very much.

**Comment by yoshitomo-matsubara** [comment]
Hi @AndyFrancesco29 ,

A main concept in torchdistill is "one configuration (file) -> one method (experiment)".
In other words, you can switch methods by different config files. For example, you can take a look at [these sample configs for ImageNet, including vanilla KD and FitNet](https://github.com/yoshitomo-matsubara/torchdistill/tree/main/configs/sample/ilsvrc2012), and will notice the main differences are loss function and layers to extract their input/output to compute the loss values (e.g., layer3 and layer4 in ResNet-34 and 18 for [Attention Transfer sample config](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/sample/ilsvrc2012/single_stage/at/resnet18_from_resnet34.yaml#L72-L83)).
Basically, (almost) all the hyperparameters and configs are defined in the yaml file, which enables you to easily see differences in methods (by comparing the yaml config files).

You could think `--config <config file>` in torchdistill as `--distill <method name>` in RepDistiller.
While RepDistiller requires hardcoding everything (models, extracting intermediate input/output, losses, datasets, etc), torchdistill provides more flexibility to allow you design these things in a yaml config file i.e., without writing Python code in many cases.

With torchdistill, you can also easily use models beyond torchvision by specifying PyTorch hub params in the yaml config file e.g., [pretrained ResNeSt-50 as a teacher](https://github.com/rwightman/pytorch-image-models) imported from [pytorch-image-models](https://github.com/rwightman/pytorch-image-models).

**Comment by AndyFrancesco29** [comment]
Thanks! I think I get that.

**Comment by AndyFrancesco29** [comment]
Hi @yoshitomo-matsubara ,
Thank you very much for your patience! Right now I am working on SSKD (KD meets self-supervised learning). I have seen you have implemented one with Imagenet, and I want to apply that for CIFAR dataset. In this paper it requires one image to be rotated and then transform. So for one original image there will be four transformed images (rotate 0, 90, 180, 270). I am wondering how you implement this part?
Also in stage one it should only update the SS module for teacher model. In the second stage it updates student network. Could you tell me where you implement these two stages? 
Again thank you very much.

**Comment by AndyFrancesco29** [comment]
Hi @yoshitomo-matsubara ,
Thank you very much for your patience! Right now I am working on SSKD (KD meets self-supervised learning). I have seen you have implemented one with Imagenet, and I want to apply that for CIFAR dataset. In this paper it requires one image to be rotated and then transform. So for one original image there will be four transformed images (rotate 0, 90, 180, 270). I am wondering how you implement this part?
Also in stage one it should only update the SS module for teacher model. In the second stage it updates student network. Could you tell me where you implement these two stages? 
Again thank you very much.

**Comment by yoshitomo-matsubara** [comment]
Hi @AndyFrancesco29 ,

For SSKD, you can refer to [this yaml config file](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/official/ilsvrc2012/yoshitomo-matsubara/rrpr2020/sskd-resnet18_from_resnet34.yaml) and README in [this directory](https://github.com/yoshitomo-matsubara/torchdistill/tree/main/configs/official/ilsvrc2012/yoshitomo-matsubara/rrpr2020).

The image rotation part is implemented as part of DataLoader wrapper [here](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/datasets/wrapper.py#L101-L115) and you will find the `SSKDDatasetWrapper` defined in the above yaml config file as well.

For the multi-stage setting, I defined so in the same yaml config file (as part of `stage1` and `stage2` entries).
At the 1st stage, some part (SS module) of the teacher model is trained as `SSWrapper4SSKD` defined in both the yaml config file and [Python code](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/models/special.py#L353-L393) while the student model is "empty" for saving training time since the student model is not necessary at the 1st stage.
At the 2nd stage, both teacher and student models use `SSWrapper4SSKD` while teacher model is frozen at this point.

If you would like to apply it for CIFAR datasets, you can update the dataset entry with CIFAR as described in other CIFAR sample configs (e.g., [this one](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/sample/cifar100/kd/wide_resnet40_1_from_wide_resnet40_4-hyperparameter_tuning.yaml)) and replace the teacher and student models with some of those [here](https://github.com/yoshitomo-matsubara/torchdistill/releases/tag/v0.1.1) (designed for CIFAR datasets with pretrained weights for teacher).

**Comment by AndyFrancesco29** [comment]
Hi @yoshitomo-matsubara ,

Thanks for your reply. I have followed your instruction and write my own config. Right now I am stuck in stage 1. I use resnet18 as student and resnet 32x4 as teacher (implemented as in SSKD/models). According to my understanding, in stage 1 although we only update teacher SS module, we still need to validate student network (in example/image_classification.py line 122). However when I got into evaluate function, and run output = model(image) (line 87), it shows me error:

`RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.`

I have set the batch size to 16 and it should not have memory issue (since training SS module for resnet32x4 is successful). Before run this code is also shows several warnings:

Warning: Leaking Caffe2 thread-pool after fork.

For the student network I still use the same configuration [as here](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/official/ilsvrc2012/yoshitomo-matsubara/rrpr2020/sskd-resnet18_from_resnet34.yaml), and I believe resnet18 is from torchvision so I am not sure why this happens. 

I attach my yaml file here if it is convenient.
[sskd-resnet18_from_resnet32x4.zip](https://github.com/yoshitomo-matsubara/torchdistill/files/6815060/sskd-resnet18_from_resnet32x4.zip). I store my data in path like "./data/cifar-100-python/train". Thanks a lot if you can help me with that.

**Comment by yoshitomo-matsubara** [comment]
Hi @AndyFrancesco29 ,

> According to my understanding, in stage 1 although we only update teacher SS module, we still need to validate student network (in example/image_classification.py line 122).

Yes, but the validated student model at line 122 is the global student model defined as `student_model` in `models`, not the local student model (`EmptyModule` at `stage1`). Thus, the above RuntimeError is not caused by the `EmptyModule`.

In you yaml file,
```
models:
  teacher_model:
    name: &teacher_model_name 'resnet32x4'
    params:
      num_classes: 100
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: './save/models/resnet32x4_vanilla/ckpt_epoch_240.pth'
  student_model:
    name: &student_model_name 'resnet18'
    params:
      num_classes: 100
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./cifar/sskd/', *student_experiment, '.pt']
```
you attempt to define the global teacher and student models as `resnet32x4` (should not be in torchdistill by default) and `resnet18` (from torchvision by default) respectively.
But, did you edit some of my python code and add `resnet32x4` to the registry of model by adding `@register_model_func` decorator like [this](https://github.com/yoshitomo-matsubara/torchdistill/blob/main/torchdistill/models/classification/resnet.py#L187)?

Also, `resnet18` in torchvision is designed for ImageNet dataset (input shape: 3x224x224) and should not work for CIFAR datasets (input shape: 3x32x32) even with `num_classes: 100` due to the smaller input. This is why I suggested [here](https://github.com/yoshitomo-matsubara/torchdistill/issues/132#issuecomment-879187463) you use some of the models designed for CIFAR datasets. 

To test SSKD for CIFAR-100, try this model config instead:
```
models:
  teacher_model:
    name: &teacher_model_name 'resnet56'
    params:
      pretrained: True
      num_classes: 100
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: './save/models/resnet56_vanilla/ckpt_epoch_240.pth'
  student_model:
    name: &student_model_name 'resnet20'
    params:
      pretrained: False
      num_classes: 100
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_from_', *teacher_model_name]
    ckpt: !join ['./cifar/sskd/', *student_experiment, '.pt']
```

You will use `resnet56` in torchdistill as a teacher and automatically download its pretrained weight as `pretrained: True` for training a student model `resnet20` in torchdistill.

I think the warning message about Caffe appears because of [this](https://github.com/pytorch/pytorch/issues/57273), which used to be a normal behavior but recent PyTorch update somehow print such messages.

Next time, provide the command you executed to get the error message.
