### ISSUE TITLE
Combine two distillation losses

### ISSUE THREAD

**Issue by shwinshaker** [yoshitomo-matsubara/torchdistill#215]
Hi,

Thanks for your amazing work.
I have a question about how to combine two or more distillation losses. 
For example, how can I set the config files such that I can use CRD and KD together, as mentioned in CRD paper?  
I looked up for a while and couldn't find the solution. 
Would really appreciate your reply. Thanks again!

**Comment by yoshitomo-matsubara** [comment]
Hi @shwinshaker 

For questions, please use `Discussions` tab above. As explained in README, I want to keep `Issues` mainly for bug reports.

For CRD + KD, you can refer to this part
https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/sample/ilsvrc2012/single_stage/crd/resnet18_from_resnet50.yaml#L128-L151

If I remember correctly, the CRD paper doesn't well describe the implementation of CRD+KD (e.g., is it multi-stage? if single-stage and just a linear combination, how did they weight each loss value?), so I assume that it's a single-stage training and linear combination of losses o CRD and KD.

You can refer to more examples available in sample configs such as https://github.com/yoshitomo-matsubara/torchdistill/blob/main/configs/sample/ilsvrc2012/single_stage/ghnd/custom_resnet152_from_resnet152.yaml#L105-L152

**Comment by shwinshaker** [comment]
Hi @yoshitomo-matsubara,

I am sorry I didn't notice this in the readme. I will move to the discussion next time. 

And thanks for the link. I just want to confirm that the following config means 

FinalLoss = factor(2.0) * KDLoss + factor(0.8) * CRDLoss, 
where
KDLoss = alpha * CrossEntropy(logits, label) + (1 - alpha) * KLDiv(logits, teacher_predictions).

Is my understanding correct?


```  
criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'KDLoss'
        params:
          temperature: 4.0
          alpha: 0.5
          reduction: 'batchmean'
      factor: 2.0
    sub_terms:
      crd:
        criterion:
          type: 'CRDLoss'
          params:
            teacher_norm_module_path: 'normalizer'
            student_norm_module_path: 'normalizer'
            student_empty_module_path: 'empty'
            input_size: *feature_dim
            output_size: &num_samples 1281167
            num_negative_samples: *num_negative_samples
            num_samples: *num_samples
            temperature: 0.07
            momentum: 0.5
            eps: 0.0000001
        factor: 0.8
```
